# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

notifications:
  commits: commits@stormcrawler.apache.org
  issues: dev@stormcrawler.apache.org
  pullrequests: dev@stormcrawler.apache.org

publish:
  profile: ~
  whoami: asf-site

github:
  description: "Source for the Apache StormCrawler web site"
  homepage: https://stormcrawler.apache.org/
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: false
   
